.PHONY: build test vet tidy clean install install-unchecked install-preload interposer

BIN := veto
PKG := ./cmd/veto

# Version metadata is injected into the binary via -ldflags -X so
# `veto --version` can report the build provenance. VERSION prefers an
# annotated tag (`git describe`), falls back to the short commit SHA,
# and gets a "-dirty" suffix when the working tree has uncommitted
# changes. The `2>/dev/null || echo …` form keeps the build working in
# tarballs / CI shallow clones that lack git metadata.
VERSION ?= $(shell git describe --tags --always --dirty 2>/dev/null || echo dev)
COMMIT  ?= $(shell git rev-parse --short HEAD 2>/dev/null || echo unknown)
DATE    ?= $(shell date -u +%Y-%m-%dT%H:%M:%SZ)
LDFLAGS := -s -w \
	-X main.version=$(VERSION) \
	-X main.commit=$(COMMIT) \
	-X main.buildDate=$(DATE)

# The interposer C source lives in a subdirectory (internal/interposer/csrc/)
# so the parent Go package (internal/interposer/) can host embed.go without
# triggering Go's "C source files not allowed when not using cgo" error.
# embed.go references csrc/* via go:embed; the Makefile compiles the same
# files directly with $(CC). Keep both sides in sync.
INTERPOSER_SRC := internal/interposer/csrc/veto_interpose.c
# Header generated by `go generate ./internal/interposer/...` from
# internal/packagemanager/pmlist.InterposerPMs. The C source #includes
# this header, so a stale or missing pm_names.h breaks the build until
# the generator runs. We list it as an explicit prereq below so a
# fresh `make interposer` regenerates it before invoking $(CC).
INTERPOSER_HEADER := internal/interposer/csrc/pm_names.h

# Per-OS shared library output. The .dylib/.so name is referenced from
# install-preload.go — keep both sides in sync.
UNAME_S := $(shell uname -s)
UNAME_M := $(shell uname -m)
ifeq ($(UNAME_S),Darwin)
	INTERPOSER_OUT := libveto_interpose.dylib
	# On Apple Silicon, system shells like /bin/sh and /bin/bash are
	# built for arm64e (Apple's pointer-auth ABI variant). When the
	# spawner exec's such a shell, dyld in the child process tries to
	# load DYLD_INSERT_LIBRARIES and refuses any non-arm64e dylib. We
	# build a fat dylib so the same artifact loads into both arches.
	ifeq ($(UNAME_M),arm64)
		INTERPOSER_CFLAGS := -O2 -Wall -Wextra -fno-common -dynamiclib -arch arm64 -arch arm64e
	else
		INTERPOSER_CFLAGS := -O2 -Wall -Wextra -fno-common -dynamiclib
	endif
else
	INTERPOSER_OUT := libveto_interpose.so
	INTERPOSER_CFLAGS := -O2 -Wall -Wextra -fPIC -shared
endif

# The build target depends on pm_names.h because cmd/veto embeds the
# interposer C source (veto_interpose.c + pm_names.h) via go:embed so
# `veto install-all` can rebuild the native library from any CWD without
# the veto source tree on disk. A missing or stale header would either
# break the embed compile or bake a drifted artifact into the binary.
build: $(INTERPOSER_HEADER)
	go build -trimpath -ldflags="$(LDFLAGS)" -o $(BIN) $(PKG)

# Run the suite without veto's own runtime interposer loaded. Several tests
# t.Setenv("VETO_PATH") to verify env-stripping; with the interposer dylib
# loaded in the test process (a preload-enabled shell, e.g. after
# `veto install-preload`), it reads that VETO_PATH via getenv and hijacks the
# tests' fake package-manager execs (exit 0 -> veto re-entry -> exit 70),
# which otherwise breaks `make install`'s test gate. The interposer's own
# e2e tests build their preloaded child env explicitly, so clearing the
# ambient preload here is safe.
test: $(INTERPOSER_HEADER)
	DYLD_INSERT_LIBRARIES= LD_PRELOAD= go test -race ./...

vet:
	go vet ./...

tidy:
	go mod tidy

clean:
	rm -f $(BIN) coverage.out coverage.html $(INTERPOSER_OUT)

# `make install` gates on the full test suite (with -race). veto is a
# security tool; shipping a build whose race detector or invariants are
# broken is exactly the failure mode it exists to prevent. For the rare
# case where the user needs to push past a known-failing test (e.g.
# during an active incident response), `make install-unchecked` skips
# the dependency.
install: test build
	install -m 0755 $(BIN) $(HOME)/.local/bin/$(BIN)

install-unchecked: build
	@echo "warning: install-unchecked skips tests — only use during an incident response or known-broken-test situation."
	install -m 0755 $(BIN) $(HOME)/.local/bin/$(BIN)

# `make interposer` builds the native shared library that intercepts
# execve/posix_spawn for direct-child-process coverage. See
# internal/interposer/veto_interpose.c for the design rationale and
# `veto install-preload` for installation.
#
# Build order: the C source #includes pm_names.h, which is regenerated
# from the canonical Go PM list (internal/packagemanager/pmlist). The
# Make recipe declares pm_names.h as an explicit prereq so a touched
# pmlist.go regenerates the header before the next compile.
interposer: $(INTERPOSER_OUT)

# pm_names.h is force-regenerated on every `make interposer` so that
# *any* change to pmlist (even via `go mod`-pulled deps in future) is
# reflected in the C build. The .PHONY-style approach is intentional:
# the generator is sub-second, and a missed regeneration is the exact
# drift hazard this whole thing exists to prevent.
.PHONY: $(INTERPOSER_HEADER)
$(INTERPOSER_HEADER):
	go generate ./internal/interposer/gen/...

# The compiled artifact lives in the repo root next to the Makefile —
# both for backwards compat with `veto install-preload --lib ./libveto_interpose.*`
# and because the .gitignore already excludes it at that path.

$(INTERPOSER_OUT): $(INTERPOSER_SRC) $(INTERPOSER_HEADER)
	$(CC) $(INTERPOSER_CFLAGS) -o $@ $<

install-preload: interposer build
	./$(BIN) install-preload --lib $(PWD)/$(INTERPOSER_OUT)
